AWSTemplateFormatVersion: '2010-09-09'
Resources:
  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "floci-demo-bucket"
  DemoQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "floci-demo-queue"
Outputs:
  BucketName:
    Value: !Ref DataBucket
